# Generated by Django 4.2.7 on 2023-11-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_number', models.CharField(max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
