# Generated by Django 4.2.7 on 2023-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='barcode_type',
            field=models.CharField(default='TipoDesconhecido', max_length=50),
        ),
    ]
