# Generated by Django 4.2.7 on 2023-12-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_barcode_barcode_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='scanned_at',
            new_name='data_escaneamento',
        ),
    ]
